 SELECT REMTAB.REGTID, PATTAB.VIKT, PATTAB.SIGNDATUMTID, 
         PATTAB.UNDSLUTDATUMTID,
         REMTAB.PRODKOD, REMTAB.TURKLASS, PATTAB.REMISSNR

         FROM PATTAB INNER JOIN REMTAB ON 
         PATTAB.REMISSNR = REMTAB.REMISSNR 
         
		 WHERE 
         PATTAB.UNDSLUTDATUMTID > '2015-01-12'
         and 
		 PATTAB.UNDSLUTDATUMTID < '2015-01-13'
